export const blockchains = [
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Aeternity",
    slug: "aeternity",
    apiSlug: "aeternity",
    icon: "/blockchains/aeternity.svg",
    placeholder: "ak_... address",
    coin: "AE",
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Aptos",
    slug: "aptos",
    apiSlug: "aptos",
    icon: "/blockchains/aptos.svg",
    placeholder: "0x... address",
    coin: "APT",
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Arbitrum One",
    slug: "arbitrumone",
    apiSlug: "arbitrumone",
    icon: "/blockchains/arbitrumone.svg",
    placeholder: "0x... address",
    coin: "ETH",
    contractAddress: "0xA6d2Dea2Aa6BA9f92048a81914e8c5395c27aB15",
    chainId: 42161,
    networkData: {
      chainId: "0xa4b1",
      chainName: "Arbitrum One",
      nativeCurrency: {
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
      },
      rpcUrls: ["https://arb1.arbitrum.io/rpc"],
      blockExplorerUrls: ["https://arbiscan.io"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Binance",
    slug: "bsc",
    apiSlug: "bsc",
    icon: "/blockchains/binance.svg",
    placeholder: "0x... address",
    coin: "BNB",
    contractAddress: "0x787aE42E3a8C6E10d6B38245f35f61eEf42A8eA8",
    chainId: 56,
    networkData: {
      chainId: "0x38",
      chainName: "Binance Smart Chain Mainnet",
      nativeCurrency: {
        name: "BNB",
        symbol: "BNB",
        decimals: 18,
      },
      rpcUrls: ["https://bsc-dataseed1.binance.org"],
      blockExplorerUrls: ["https://bscscan.com"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Celo",
    slug: "celo",
    apiSlug: "celo",
    icon: "/blockchains/celo.svg",
    placeholder: "0x... address",
    coin: "CELO",
    contractAddress: "0x361534d5ee6a1ce28add20905867eea4d02a0b04",
    chainId: 42220,
    networkData: {
      chainId: "0xa4ec",
      chainName: "Celo Mainnet",
      nativeCurrency: {
        name: "CELO",
        symbol: "CELO",
        decimals: 18,
      },
      rpcUrls: ["https://forno.celo.org"],
      blockExplorerUrls: ["https://celoscan.io"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Cube",
    slug: "cube",
    apiSlug: "cube",
    icon: "/blockchains/cube.svg",
    placeholder: "0x... address",
    coin: "CUBE",
    chainId: 1818,
    networkData: {
      chainId: "0x71a",
      chainName: "Cube Chain Mainnet",
      nativeCurrency: {
        name: "CUBE",
        symbol: "CUBE",
        decimals: 18,
      },
      rpcUrls: ["https://http-mainnet.cube.network"],
      blockExplorerUrls: ["https://www.cubescan.network"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Ethereum",
    slug: "ethereum",
    apiSlug: "ethereum",
    icon: "/blockchains/ethereum.svg",
    placeholder: "0x... or .eth",
    coin: "ETH",
    contractAddress: "0x361534d5ee6a1ce28add20905867eea4d02a0b04",
    chainId: 5,
    networkData: {
      chainId: "0x5",
      chainName: "Сеть Ethereum Goerli",
      nativeCurrency: {
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
      },
      rpcUrls: ["https://mainnet.infura.io/v3/"],
      blockExplorerUrls: ["https://goerli.etherscan.io"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Evmos",
    slug: "evmos",
    apiSlug: "evmos",
    icon: "/blockchains/evmos.svg",
    placeholder: "0x... address",
    coin: "EVMOS",
    contractAddress: "0x361534d5ee6a1ce28add20905867eea4d02a0b04",
    chainId: 9001,
    networkData: {
      chainId: "0x2329",
      chainName: "Evmos",
      nativeCurrency: {
        name: "EVMOS",
        symbol: "EVMOS",
        decimals: 18,
      },
      rpcUrls: ["https://eth.bd.evmos.org:8545"],
      blockExplorerUrls: ["https://evm.evmos.org"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Hedera",
    slug: "hedera",
    apiSlug: "hedera",
    icon: "/blockchains/hedera.svg",
    placeholder: "Wallet address",
    coin: "HBAR",
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Klaytn",
    slug: "klaytn",
    apiSlug: "klaytn",
    icon: "/blockchains/klaytn.svg",
    placeholder: "0x... address",
    coin: "KLAY",
    contractAddress: "0x948a02abb83ed54d8908f6725d2a9cee6b6b582a",
    chainId: 8217,
    networkData: {
      chainId: "0x2019",
      chainName: "Klaytn Mainnet Cypress",
      nativeCurrency: {
        name: "KLAY",
        symbol: "KLAY",
        decimals: 18,
      },
      rpcUrls: ["https://public-node-api.klaytnapi.com/v1/cypress"],
      blockExplorerUrls: ["https://scope.klaytn.com"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Moonbeam",
    slug: "moonbeam",
    apiSlug: "moonbeam",
    icon: "/blockchains/moonbeam.svg",
    placeholder: "0x... address",
    coin: "GLMR",
    contractAddress: "0x948a02ABB83ED54D8908F6725d2a9cEE6B6B582a",
    chainId: 1284,
    networkData: {
      chainId: "0x504",
      chainName: "Moonbeam",
      nativeCurrency: {
        name: "GLMR",
        symbol: "GLMR",
        decimals: 18,
      },
      rpcUrls: ["https://rpc.api.moonbeam.network"],
      blockExplorerUrls: ["https://moonbeam.moonscan.io"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Polygon",
    slug: "polygon",
    apiSlug: "polygon",
    icon: "/blockchains/polygon.svg",
    placeholder: "0x... address",
    coin: "MATIC",
    contractAddress: "0x2e4c7f1914B4d17b23C1c034ea384eD345562C7D",
    chainId: 137,
    networkData: {
      chainId: "0x89",
      chainName: "Polygon Mainnet",
      nativeCurrency: {
        name: "MATIC",
        symbol: "MATIC",
        decimals: 18,
      },
      rpcUrls: ["https://polygon-rpc.com"],
      blockExplorerUrls: ["https://polygonscan.com"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Ripple",
    slug: "ripple",
    apiSlug: "ripple",
    icon: "/blockchains/ripple.svg",
    placeholder: "r... address",
    coin: "XRP",
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Solana",
    slug: "solana",
    apiSlug: "solana",
    icon: "/blockchains/solana.svg",
    placeholder: "Wallet address",
    coin: "SOL",
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Tron",
    slug: "tron",
    apiSlug: "tron",
    icon: "/blockchains/tron.svg",
    placeholder: "Wallet address",
    coin: "TRX",
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Trust EVM",
    slug: "trustevm",
    apiSlug: "trustevm",
    icon: "/blockchains/trustevm.svg",
    placeholder: "0x... address",
    coin: "ETH",
    contractAddress: "0x361534d5ee6a1ce28add20905867eea4d02a0b04",
    chainId: 15555,
    networkData: {
      chainId: "0x3cc3",
      chainName: "Trust Network Testnet Preview",
      nativeCurrency: {
        name: "EVM",
        symbol: "EVM",
        decimals: 18,
      },
      rpcUrls: ["https://api.testnet-dev.trust.one"],
      blockExplorerUrls: ["https://trustscan.one"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Waves",
    slug: "waves",
    apiSlug: "waves",
    icon: "/blockchains/waves.svg",
    placeholder: "Wallet address",
    coin: "Waves",
  },
  {
    group: "eco",
    groupLabel: "Eco",
    item: "Polygon",
    slug: "polygon_eco",
    apiSlug: "polygon",
    icon: "/blockchains/polygon.svg",
    placeholder: "0x... address",
    coin: "MATIC",
    contractAddress: "0x2e4c7f1914B4d17b23C1c034ea384eD345562C7D",
    chainId: 137,
    networkData: {
      chainId: "0x89",
      chainName: "Polygon Mainnet",
      nativeCurrency: {
        name: "MATIC",
        symbol: "MATIC",
        decimals: 18,
      },
      rpcUrls: ["https://polygon-rpc.com"],
      blockExplorerUrls: ["https://polygonscan.com"],
    },
  },
];
